### ISSUE TITLE
Is a National ID Required?

### ISSUE THREAD

**Issue by rmehta** [mosip/documentation#4]
Hello folks,

Firstly we appreciate your opening up this code base. Its a great first step and thank you for your willingness to engage. I would like to raise a more fundamental issue that is important to the architecture of this project. 

*Do we need a centralized identity system?*

Some of the major problems I can see are:

- The tool assumes that a government entity is aligned with the needs of its people.
- The tool assumes that partisans will not use such a system to systematically target its political opponents.
- The tool assumes that it will be used for empowerment rather than discrimination. Any tool that is used to "authenticate" a welfare service, can also be used to "deny" it.

How do the creators of this project view these ethical dilemmas? Will this result in inadvertently creating a tool for authoritarian and tyrannical regimes to oppress its opponents?

Are the alternatives effectively debated? Will the citizens of the countries implementing such systems have consent in adopting it?

Will be happy to get some answers here!

**Comment by ssenmosip** [comment]
Thank you for your questions and engaging with us, we really appreciate it. The MOSIP Project's position is not to push national digital ID globally - that is for each country and its people to decide for themselves. We do believe however that **if** a country chooses to adopt a national ID system -- after proper debate, people's participation and enactment of laws and regulations -- then adoption of a system that is open to scrutiny and feedback is a better alternative than a closed system with no visibility into its workings.

The questions you have raised on how a digital ID system can be used by governments are extremely important and we've been thinking hard about them as well. We don't pretend to have complete answers, but here is our thinking at the moment - as creators of an open source codebase, we are not experts on the rights and needs of people around the world. This does not mean that we abdicate responsibility for how the codebase is going to be used. It does mean that we work together with organisations and people who are better placed than we are to shape the formation of digital ID systems that work for people. This includes digital rights organisations and groups that work globally as well as in the countries where MOSIP may be implemented. 

We thought long and hard about placing conditionalities on the use of the codebase itself, but ultimately thought that this would be against the ethos of open source code. The assistance of the MOSIP Project itself, though, will be in accordance with the Principles of Identification for Sustainable Development. [More on our position on this is available here.](https://www.mosip.io/uploads/resources/5cc84b0a08284Country%20Engagement%20Principles_v2.pdf)

**Comment by rmehta** [comment]
@ssenmosip Thanks for the reply!

>> then adoption of a system that is open to scrutiny and feedback is a better alternative than a closed system with no visibility into its workings.

So MOSIP while fully open source, is not a project that has scope for participation. For example, a public issue tracker is a basic requirement.

Some of the decisions you make are very important to how the system is implemented and lack of a public discussion forum, make it hard for someone later on to trust and comment on. There is a "cloak of secrecy". Let me help you with a extreme example. All of Gandhi's works, private letters etc have been saved and published in 99 volumes for public to scrutinize. Maybe that was one of the way he built trust, so people could then scrutinize if he had an hidden agenda.

Also MOSIP is not a result of a "public movement" (in fact the movement is against it) but an idea that comes from deep within the establishment. The hidden agenda for this secrecy could be (and this is just speculative) that only certain vendors would be notified of the architecture so they would be prepared to bid when the RFPs are open. If you were aware of the impact of your work, the transparency and discussions should have started way earlier.

While I appreciate the interest to engage at such a late point, it would build a lot of trust if you open your internal issue tracker and financial position transparently including all expenses and salaries paid. Other than IIITB there is no other organization that is officially engaged here so it is hard to know whose agenda is being followed here. I am sure a lot of people have good intentions at MOSIP but there is still a long way to go before there will be engagement.

Infact your outreach activity and funds should be directed towards the countries who are your potential clients and to build a vendor and community ecosystem in those countries, so they don't be dependent on foreign capital. Also MOSIP being a "community" project should also be at the forefront of the fight for opening up India's UIDAI and other architectures so that it becomes more open.

These are all basic questions I am collating from many people, and personally I have no bandwidth to engage with MOSIP or any other agenda. That's it from me now, I will leave it to your team to internally debate and take this forward.
