### ISSUE TITLE
Allowing Multiple IDs

### ISSUE THREAD

**Issue by rmehta** [mosip/documentation#7]
Virtualized IDs are a way to ensure that the national ID is not used to connect a person across systems but is extremely inconvenient for a citizen to handle a new ID for every scenario. And even in this case, a centralized system can still link the virtual IDs to a single person. 

Can an option to let the system accept multiple IDs for the same person be evaluated?

It would mean that it would not be possible to "uniquely" identify a person, but it would still be used as a "proof of identity"

This would be like a person enrolling for multiple credit cards or bank accounts that are independent.

**Comment by srikanthlogic** [comment]
I asked this at the last community outreach webminar - [Link](https://zoom.us/recording/play/GSWnvtI3wMIKD3Tig3MeuRgCGGUOz0CPTHo9dUVLL8oQIxyzahuytImAtBrntiZ9?continueMode=true) at 27 minutes

Q : Does configurability allow the system to issue multiple IDs or is deduplication / uniqueness is hardbaked?

A : (Poor audio quality) - Difference between foundational IDs and functional IDs. MOSIP is foundational ID system and not a functional ID. Users can have choice of using Virtual IDs. Yes .... is hardbaked.

**Comment by hosurkrishnan** [comment]
Well multiple IDs are possible with MOSIP with virtual IDs where one could have multiple virtual IDs against one primary unique ID.

**Comment by gsasikumar** [comment]
The eventual thoughts are that the data is encrypted in a way that only a
person with virtual identity can decrypt. Now with this, if we remove any
mapping to the virtual id and we take the virtual id as an ID that exists
for a point in time with no linkage then we can achieve this behaviour. We
need to rethink about this in a clear way. we have to ensure
non-repudiablity with good privacy.


Thanks
Sasikumar Ganesan
https://www.linkedin.com/in/sasikumarganesan/
https://twitter.com/g_sasi_kumar
