### ISSUE TITLE
Is there a non-public bug-tracker, discussion forum or a mailing list?

### ISSUE THREAD

**Issue by nileshtrivedi** [mosip/documentation#8]
Have a look at this PR: https://github.com/mosip/id-authentication/pull/2

There is a bug identifier MOS-30337 and no description of the issue whatsoever. It seems to refer to a separate issue tracker that I can't find a reference to on the site. 

Similar instances here:
https://github.com/mosip/commons/pull/7
https://github.com/mosip/commons/pull/6

Some of these PRs are being merged as well: https://github.com/mosip/commons/pull/2

Can you please enumerate all the forums where issues are tracked, discussed and debated? This should include forums, chat groups, mailing lists etc. This will be essential for the community to feel welcome and engaged via transparency and inclusiveness.

**Comment by hosurkrishnan** [comment]
The MOS IDs that you see in code point to JIRA tickets that were used as part of our development.   Atlassian was kind enough to give us an open source license to use JIRA for issue tracking although github issues could have been used,  JIRA has better features that we would lke to leverage.

We are working with them to give public bowse rights for anyone to browse the issues from the community without having to have an atlassian JIRA account.   This has to be enabled by Atlassian - will happen in few days.

The forums for MOSIP
We are on groups.io and gitter.   Information regarding how to join them can be got from repo readme
https://github.com/mosip/documentation

Thanks for your feedback Nilesh.   Really appreciate that.   These queries are useful in improving MOSIP.

**Comment by nileshtrivedi** [comment]
Potential contributors will want and need the right to "contribute" and not just "browsing rights". If the key decisions are being made behind the scenes with no opportunity for the community to have a say, I'm afraid this project is not _open_ at all.

I urge you to get a JIRA license that allows you the wider community to have right to comment, attach bug reports etc. Even better, you can consider using GitHub, GitLab, Bugzilla or Redmine for managing your issues. You can take a look at how [Mozilla](https://developer.mozilla.org/en-US/docs/Mozilla/Bugzilla) and [Ruby](https://bugs.ruby-lang.org/) projects manage their communities.

**Comment by hosurkrishnan** [comment]
Agree with you Nilesh.
